spring:
  application:
    name: anti-fraud-app

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

  liquibase:
    enabled: true

  eureka:
    client:
      register-with-eureka: true

    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30



